# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://iammueller.com" # the base hostname & protocol for your site
permalink: /:categories/:title

title: I AM MUELLER
description: > # this means to ignore newlines
  The personal website of Chris Mueller, an interaction designer and software developer.

collections:
  - shorts

# Build settings
markdown: kramdown
